INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (18, 'Mariusz', 'Pastuszka');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (25, 'Mariusz', 'Pastuszka');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (40, 'Mariusz', 'Pastuszka');