INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (18, 'Mariusz', 'Pastuszka');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (25, 'Mariusz', 'Pastuszka');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (40, 'Mariusz', 'Pastuszka');

INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES ('Computer', 1000);
INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES ('CoffeeMachine', 459.99);
INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES ('Chair', 149.99);